version: "3"
services:
  web:
    image: nginx:1.17.8-alpine
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./cooking/public:/var/www/cooking/public

  app:
    build: ./docker/app
    volumes:
      - ./cooking:/var/www/cooking
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.19
    volumes:
      - "./docker/mysql/mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}